### ISSUE TITLE
m5paper - solar dashboard

### ISSUE THREAD

**Issue by kovi44** [Bastelschlumpf/IslandSolarPlant#1]
Hi,

let me say, that I really like your pv dashboard. I would like to implement your piece of code / software also for my Huawei inverter. I got mqtt reports from inverter. I just checked your code and I understand it correctly then you use some kind of IObroker as mediator between mqtt and m5paper. Did  you consider to connect it directly with mqtt? Is there any limitation? Or whz did you decide to handle it via iobroker?
Thanks
Lukas

**Comment by Bastelschlumpf** [comment]
Hello,

If your Huawei inverter has the possibility to connect to a MQTT 
server then it should be no problem to display the data later on a M5Paper.
later.

IoBroker is a home control software that runs on a Raspberry for me.
Have a look at https://www.iobroker.net
My inverter is not able to send MQTT so I had to realize the mqqtbridge
with an ESP32.

With my IoBroker there is a MQTT adapter which serves as a server and here you can 
activate a history function for the received values, so that you can check the 
history data.
Then you have to install a so called 'simple-api' adapter with which you can use a simple 
simple http query and get the IoBroker data back as json.

http://server:port/query/mqtt.0.bmv.H17?dateFrom=2022-12-06T12:00:00.000Z&dateTo=2023-01-06T12:00:00.000Z&count

In the M5Paper ESP32 I then read the desired MQTT data and display it using canvas.

I hope the information helps.
Greetings Ebby
